---
os: osx

install:
  - sudo easy_install pip
  - sudo pip install ansible
  - ansible --version

script:
  - ./test.yml --inventory localhost, --connection local

after_failure:
  - sed -n '/Uninstall-MacKeeper/,$p' /var/log/install.log
