---
os: osx

install:
  - sudo easy_install pip
  - sudo pip install ansible
  - ansible --version
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install shellcheck

script:
  - shellcheck *.sh uninstaller/*
  - ./test.yml --inventory localhost, --connection local

after_failure:
  - sed -n '/Uninstall-MacKeeper/,$p' /var/log/install.log
