#!/usr/bin/env ansible-playbook
---
- name: Test MacKeeper Uninstaller Package
  hosts: all
  tasks:
    - name: Open MacKeeper
      command: open -a MacKeeper
      become_user: '{{ ansible_user }}'
      ignore_errors: yes

    - name: Build package
      command: ./build_package.sh
      delegate_to: localhost
      register: build_package

    - set_fact:
        local_package_path: '{{ build_package.stdout }}'
        remote_package_path: '/tmp/{{ build_package.stdout | basename }}'

    - name: Upload package
      copy:
        src: '{{ local_package_path }}'
        dest: '{{ remote_package_path }}'

    - name: Install package
      command: installer -tgt / -pkg '{{ remote_package_path }}'

    - name: MacKeeper should not be running
      command: pgrep -ix mackeeper
      changed_when: no
      register: result
      failed_when: result.rc != 1

    - name: MacKeeperAgent should not be running
      command: pgrep -ix mackeeperagent
      changed_when: no
      register: result
      failed_when: result.rc != 1

    - name: MacKeeper's system paths should be absent
      command: test ! -e '{{ item }}'
      changed_when: no
      with_items:
        - /Applications/MacKeeper.app
        - /Library/Preferences/.3FAD0F65-FC6E-4889-B975-B96CBF807B78

    - name: MacKeeper's user paths should be absent
      command: test ! -e '{{ item }}'
      changed_when: no
      with_items:
        - Library/Application Support/com.mackeeper.MacKeeper
        - Library/Application Support/com.mackeeper.MacKeeperAgent
        - Library/Application Support/MacKeeper
        - Library/Saved Application State/com.mackeeper.MacKeeper.savedState
        - Library/Preferences/com.mackeeper.MacKeeper.plist
        - Library/Preferences/com.mackeeper.MacKeeperAgent.plist
        - Library/Logs/MacKeeper
        - Library/LaunchAgents/com.mackeeper.MacKeeperAgent.plist
        - Library/Caches/com.crashlytics.data/com.mackeeper.MacKeeperUninstaller
        - Library/Caches/com.crashlytics.data/com.mackeeper.MacKeeper
        - Library/Caches/com.crashlytics.data/com.mackeeper.MacKeeperAgent
        - Library/Caches/com.apple.nsurlsessiond/Downloads/com.mackeeper.MacKeeperUninstaller
        - Library/Caches/com.apple.nsurlsessiond/Downloads/com.mackeeper.MacKeeper
        - Library/Caches/com.apple.nsurlsessiond/Downloads/com.mackeeper.MacKeeperAgent
        - Library/Caches/io.fabric.sdk.mac.data/com.mackeeper.MacKeeperUninstaller
        - Library/Caches/io.fabric.sdk.mac.data/com.mackeeper.MacKeeper
        - Library/Caches/io.fabric.sdk.mac.data/com.mackeeper.MacKeeperAgent
        - Library/Caches/com.mackeeper.MacKeeper
        - Library/Caches/com.mackeeper.MacKeeperAgent

    - name: MacKeeper packages should be absent
      command: pkgutil --pkgs="com.mackeeper.*"
      changed_when: no
      register: result
      failed_when: result.rc != 1
