#!/bin/bash
# postinstall - Uninstall MacKeeper

export PATH='/usr/bin:/bin:/usr/sbin:/sbin'

VOLUME="$3"
USERS_PATH='/Users'
MACKEEPER_LAUNCHAGENT_PATH=\
'Library/LaunchAgents/com.mackeeper.MacKeeperAgent.plist'
MACKEEPER_SYSTEM_PATHS=(
  '/Applications/MacKeeper.app'
  '/Library/Preferences/.3FAD0F65-FC6E-4889-B975-B96CBF807B78'
)
MACKEEPER_USER_PATHS=(
  'Library/Application Support/com.mackeeper.MacKeeper'
  'Library/Application Support/com.mackeeper.MacKeeperAgent'
  'Library/Application Support/MacKeeper'
  'Library/Saved Application State/com.mackeeper.MacKeeper.savedState'
  'Library/Preferences/com.mackeeper.MacKeeper.plist'
  'Library/Preferences/com.mackeeper.MacKeeperAgent.plist'
  'Library/Logs/MacKeeper'
  'Library/LaunchAgents/com.mackeeper.MacKeeperAgent.plist'
)

pkill -9 -x MacKeeper

for user in $(users); do
  domain_target="gui/$(id -u "${user}")"
  service_path="${USERS_PATH:?}/${user}/${MACKEEPER_LAUNCHAGENT_PATH:?}"
  launchctl bootout "${domain_target}" "${service_path}"
done

for mackeeper_system_path in "${MACKEEPER_SYSTEM_PATHS[@]}"; do
  rm -rf "${VOLUME:?}${mackeeper_system_path:?}"
done

for user_path in "${VOLUME:?}${USERS_PATH:?}"/*; do
  [[ "${user_path##*/}" == 'Shared' ]] && continue # Skip shared user folder
  for mackeeper_user_path in "${MACKEEPER_USER_PATHS[@]}"; do
    rm -rf "${user_path:?}/${mackeeper_user_path:?}"
  done
done

exit 0
