#!/bin/bash
# postinstall - Uninstall MacKeeper

export PATH=/usr/bin:/bin:/usr/sbin:/sbin

SYSTEM_PATHS=(
  '/Applications/MacKeeper.app'
  '/Library/Preferences/.3FAD0F65-FC6E-4889-B975-B96CBF807B78'
)

pkill -9 -ix mackeeper

for system_path in "${SYSTEM_PATHS[@]}"; do
  rm -rf "${system_path}"
done

exit 0
